name: CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Start the app
        run: npm start &

      - name: Wait for the application to boot
        run: sleep 10

      - name: Check Health
        run: curl -I http://localhost:3000