name: CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Show files
        run: |
          pwd
          ls -la

      - name: Install Dependencies
        run: npm install

      - name: Start App
        run: npm start &

      - name: Wait for app
        run: sleep 10

      - name: Health Check
        run: curl -I http://localhost:3000